### ISSUE TITLE
redundant check for program id against raydium program address

### ISSUE THREAD

**Issue by nabeel-uncx** [0xpapercut/raydium-amm-substream#5]
Hey while going thru the impl, i noticed there is a redundant check 
```
  if bs58::encode(context.get_account_from_index(instruction.program_id_index as usize)).into_string() != RAYDIUM_LIQUIDITY_POOL {
  ``` 
  its done in parse_transaction when you iterate over each instruction as well as inside parse instruction over the passed instruction which at a glance seems redundant, or am i missing out on something ?

**Comment by 0xpapercut** [comment]
if someone use this function in another substream, i tend to err on the side of warning bad usage.
